# FOR WINDOWS
name: epictope
channels:
  - bioconda
  - conda-forge
dependencies:
  - dssp>=4.0.0
  - git
  - python>=3.11.4
  - pip:
    - biopython
    - pandas
    - matplotlib
    - requests
    - pyyaml
